import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { CheckCircle2, Eye, Home, Plus, Printer } from 'lucide-react-native';
import { colors, fontSize, fontWeight, radius, spacing } from '@yardflow/theme';
import { usePrinter } from '../../printing/printer.context';
import type { ReceiptData } from '../../printing/receipt.types';

export interface SuccessRow {
  label: string;
  value: string;
  accent?: 'green' | 'blue' | 'amber';
}

interface Props {
  title: string;
  receipt: ReceiptData | null;
  rows: SuccessRow[];
  isPayment?: boolean;
  allocCount?: number;
  onNew(): void;
  newLabel?: string;
}

export function TransactionSuccess({
  title,
  receipt,
  rows,
  isPayment = false,
  allocCount,
  onNew,
  newLabel = 'Record another',
}: Props) {
  const router = useRouter();
  const { savedDevice, printStatus, printReceipt, resetPrintStatus } = usePrinter();

  const isPrinting = printStatus === 'connecting' || printStatus === 'printing';
  const noPrinter = !savedDevice;

  const handlePrint = () => {
    if (!receipt) return;
    resetPrintStatus();
    void printReceipt(receipt);
  };

  const goHome = () => router.push('/');

  const openReceipt = () =>
    receipt &&
    router.push({
      pathname: '/receipt-preview',
      params: { receipt: JSON.stringify(receipt) },
    });

  return (
    <View style={styles.container}>
      {/* Hero */}
      <View style={styles.hero}>
        <View style={styles.circle}>
          <CheckCircle2 size={44} color="#fff" strokeWidth={1.5} />
        </View>
        <Text style={styles.heroTitle}>{title}</Text>
      </View>

      {/* Summary card */}
      <View style={styles.card}>
        {rows.map((r, i) => (
          <View key={i} style={[styles.row, i < rows.length - 1 && styles.rowBorder]}>
            <Text style={styles.rowLabel}>{r.label}</Text>
            <Text
              style={[
                styles.rowValue,
                r.accent === 'green' && styles.green,
                r.accent === 'blue' && styles.blue,
                r.accent === 'amber' && styles.amber,
              ]}
            >
              {r.value}
            </Text>
          </View>
        ))}
        {(allocCount ?? 0) > 0 && (
          <View style={[styles.row, styles.rowBorder]}>
            <Text style={styles.rowLabel}>Balances cleared</Text>
            <Text style={[styles.rowValue, styles.green]}>{allocCount}</Text>
          </View>
        )}
        {isPayment && (
          <View style={styles.mpesaNote}>
            <Text style={styles.mpesaText}>
              Manual record · No M-Pesa code generated by YardFlow
            </Text>
          </View>
        )}
      </View>

      {/* Print / receipt actions */}
      {receipt && (
        <View style={styles.printBlock}>
          {noPrinter ? (
            <>
              <View style={styles.noPrinterBanner}>
                <Printer size={16} color={colors.muted} strokeWidth={1.75} />
                <Text style={styles.noPrinterText}>No printer selected</Text>
              </View>
              <View style={styles.btnRow}>
                <TouchableOpacity
                  style={styles.halfBtn}
                  onPress={() => router.push('/more/printer')}
                  activeOpacity={0.8}
                >
                  <Printer size={15} color={colors.text} strokeWidth={1.75} />
                  <Text style={styles.halfBtnLabel}>Select Printer</Text>
                </TouchableOpacity>
                <TouchableOpacity style={styles.halfBtn} onPress={openReceipt} activeOpacity={0.8}>
                  <Eye size={15} color={colors.text} strokeWidth={1.75} />
                  <Text style={styles.halfBtnLabel}>View Receipt</Text>
                </TouchableOpacity>
              </View>
            </>
          ) : (
            <>
              <TouchableOpacity
                style={[styles.printBtn, isPrinting && styles.printBtnDisabled]}
                onPress={handlePrint}
                disabled={isPrinting}
                activeOpacity={0.85}
              >
                <Printer size={20} color="#fff" strokeWidth={1.75} />
                <Text style={styles.printBtnLabel}>
                  {isPrinting
                    ? 'Printing…'
                    : printStatus === 'success'
                    ? 'Print Again'
                    : 'Print Receipt'}
                </Text>
              </TouchableOpacity>
              {printStatus === 'error' && (
                <Text style={styles.printError}>Print failed — check printer connection</Text>
              )}
              <View style={styles.btnRow}>
                <TouchableOpacity style={styles.halfBtn} onPress={openReceipt} activeOpacity={0.8}>
                  <Eye size={15} color={colors.text} strokeWidth={1.75} />
                  <Text style={styles.halfBtnLabel}>View Receipt</Text>
                </TouchableOpacity>
                <TouchableOpacity style={styles.halfBtn} onPress={goHome} activeOpacity={0.8}>
                  <Home size={15} color={colors.text} strokeWidth={1.75} />
                  <Text style={styles.halfBtnLabel}>Back Home</Text>
                </TouchableOpacity>
              </View>
            </>
          )}
        </View>
      )}

      {/* Record another */}
      <TouchableOpacity style={styles.newBtn} onPress={onNew} activeOpacity={0.8}>
        <Plus size={16} color={colors.green[800]} strokeWidth={2} />
        <Text style={styles.newBtnLabel}>{newLabel}</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    paddingTop: spacing[2],
  },
  hero: {
    alignItems: 'center',
    marginBottom: spacing[5],
  },
  circle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.green[800],
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[3],
    elevation: 3,
    shadowColor: colors.green[800],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  heroTitle: {
    fontSize: fontSize.h2,
    fontWeight: fontWeight.semibold,
    color: colors.text,
    textAlign: 'center',
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    overflow: 'hidden',
    elevation: 1,
    marginBottom: spacing[4],
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing[4],
    paddingVertical: 13,
  },
  rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.border },
  rowLabel: { fontSize: fontSize.body, color: colors.muted },
  rowValue: { fontSize: fontSize.body, fontWeight: fontWeight.semibold, color: colors.text },
  green: { color: colors.green[800] },
  blue: { color: colors.blue[700] },
  amber: { color: colors.amber.text },
  mpesaNote: {
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
    backgroundColor: colors.neutral[100],
  },
  mpesaText: {
    fontSize: fontSize.caption,
    color: colors.muted,
    fontStyle: 'italic',
  },
  printBlock: {
    marginBottom: spacing[4],
  },
  noPrinterBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.neutral[100],
    borderRadius: radius.sm,
    paddingVertical: spacing[3],
    marginBottom: spacing[3],
  },
  noPrinterText: { fontSize: fontSize.bodySm, color: colors.muted },
  printBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: colors.green[800],
    borderRadius: radius.md,
    paddingVertical: 16,
    marginBottom: spacing[3],
    elevation: 2,
  },
  printBtnDisabled: { opacity: 0.6 },
  printBtnLabel: {
    fontSize: fontSize.body,
    fontWeight: fontWeight.semibold,
    color: '#fff',
  },
  printError: {
    fontSize: fontSize.caption,
    color: '#ef4444',
    textAlign: 'center',
    marginTop: -spacing[2],
    marginBottom: spacing[3],
  },
  btnRow: {
    flexDirection: 'row',
    gap: spacing[3],
  },
  halfBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: 14,
    elevation: 1,
  },
  halfBtnLabel: {
    fontSize: fontSize.bodySm,
    fontWeight: fontWeight.medium,
    color: colors.text,
  },
  newBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.green[800],
    borderRadius: radius.md,
    paddingVertical: 14,
    marginBottom: spacing[4],
  },
  newBtnLabel: {
    fontSize: fontSize.body,
    fontWeight: fontWeight.medium,
    color: colors.green[800],
  },
});
